plugins {
    id 'net.neoforged.moddev' version '2.0.148' apply false
}

allprojects {
    group = mod_group_id
    version = mod_version
}

subprojects {
    repositories {
        mavenCentral()
    }

    plugins.withType(JavaPlugin).configureEach {
        java.toolchain.languageVersion = JavaLanguageVersion.of(25)
        tasks.withType(JavaCompile).configureEach {
            options.encoding = 'UTF-8'
        }
    }
}

def artifactModId = rootProject.property('mod_id')
def artifactMinecraftVersion = rootProject.property('minecraft_version')
def artifactVersion = rootProject.property('mod_version')

// 复制并重命名发布包
def copyBuildArtifacts = tasks.register('copyBuildArtifacts', Copy) {
    group = 'build'
    description = '复制并重命名 NeoForge 发布包到根目录 build/v<版本>。'
    dependsOn ':neoforge:build'
    into layout.buildDirectory.dir("v${artifactVersion}")
    from(project(':neoforge').layout.buildDirectory.dir('libs')) {
        include "${artifactModId}-${artifactMinecraftVersion}-neoforge-${artifactVersion}.jar"
        rename { "${artifactModId}-v${artifactVersion}-mc${artifactMinecraftVersion}-neoforge.jar" }
    }
}

tasks.register('buildAll') {
    group = 'build'
    description = '构建 NeoForge 模组。'
    dependsOn copyBuildArtifacts
}

tasks.register('build') {
    group = 'build'
    description = '构建并测试通用代码与 NeoForge 模组。'
    dependsOn ':common:test', copyBuildArtifacts
}
