plugins {
    id 'java-library'
    id 'net.neoforged.moddev'
}

base {
    archivesName = "${mod_id}-common"
}

neoForge {
    version = project.neo_version
    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    compileOnly "org.jetbrains:annotations:${jetbrains_annotations_version}"
    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

sourceSets.test {
    compileClasspath += sourceSets.main.compileClasspath
    runtimeClasspath += sourceSets.main.runtimeClasspath
}

tasks.named('test', Test).configure {
    useJUnitPlatform()
}
